package com.example.myapplication

import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.MotionEvent
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.util.LinkedList

class MainActivity : AppCompatActivity() {

    // --- Global Variable Declarations ---

    // [Variable] A TextView to display instructions or feedback to the user (e.g., "My turn", "Your turn").
    lateinit var EditText: TextView

    // [Variable] The blue button in the game.
    lateinit var Button: Button // Blue

    // [Variable] The red button in the game.
    lateinit var Button2: Button // Red

    // [Variable] The green button in the game.
    lateinit var Button3: Button // Green

    // [Variable] The yellow button in the game.
    lateinit var Button4: Button // Yellow

    // [Variable] A TextView that displays the user's current progress within the sequence for the round.
    lateinit var textCount: TextView

    // [Variable - Int] A counter that tracks how many correct buttons the user has pressed in the current round.
    var count = 0

    // [Variable - Int] Stores the highest score achieved across all games. This value is passed between activities.
    var bestScore = 0

    // [Variable - Int] Determines the length of the sequence the user needs to repeat. It increments by 1 after each successful round.
    var number = 1

    // [Data Structure] A LinkedList that stores the sequence of buttons generated by the computer, which the user must memorize and repeat.
    private val sequenceToRemember: LinkedList<Button> = LinkedList()

    /**
     * [Data Structure] A Data Class that groups all the information related to a single game button.
     * @param button The Button widget object itself.
     * @param normalColor The button's default color as a hex string.
     * @param pressedColor The color to display when the button is being pressed, as a hex string.
     */
    data class ButtonColorData(
        val button: Button,
        val normalColor: String,
        val pressedColor: String,
        val tone: Int
    )

    // [Variable] A list that holds all four game buttons, along with their associated color data.
    // 'lateinit' promises that this list will be initialized before it is ever used.
    lateinit var buttonDataList: List<ButtonColorData>

    /**
     * [Main Function] onCreate - The entry point for this Activity.
     * This function is called once when the screen is first created.
     * It handles all initial setup: linking variables to XML views,
     * creating the list of button data, and retrieving the best score
     * from the previous activity to start the game.
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Connects the Kotlin code to the UI layout file (activity_main.xml).
        setContentView(R.layout.activity_main)

        // --- Initializing Widgets (linking to UI elements from the XML) ---
        EditText = findViewById(R.id.EditText)
        Button = findViewById(R.id.button)
        Button2 = findViewById(R.id.button2)
        Button3 = findViewById(R.id.button3)
        Button4 = findViewById(R.id.button4)
        textCount = findViewById(R.id.textCount)

        // --- Creating the list of buttons and their color data ---
        buttonDataList = listOf(
            ButtonColorData(Button, "#2196F3", "#1976D2", 523),   // Blue
            ButtonColorData(Button2, "#F32121", "#C11313", 587),  // Red
            ButtonColorData(Button3, "#07B417", "#058A12", 659),  // Green
            ButtonColorData(Button4, "#FFE700", "#D1BE00", 698)   // Yellow
        )

        // Retrieves the best score passed from the previous activity, defaulting to 0 if not found.
        bestScore = intent.getIntExtra("bestScore", 0)

        // This condition automatically starts the game when the activity launches.
        if (intent != null) {
            number = 1 // Resets the sequence length to 1 for a new game.
            Toast.makeText(this, "Start a new game", Toast.LENGTH_SHORT).show() // Displays a brief message.
            startSimulation() // Calls the function to start the simulation sequence.
        }
    }

    fun playTone(frequency: Int) {
        val duration = 0.4 // שניות
        val sampleRate = 8000
        val numSamples = (duration * sampleRate).toInt()
        val samples = DoubleArray(numSamples)
        val buffer = ByteArray(2 * numSamples)

        // יצירת גל קול מוזיקלי נקי
        for (i in 0 until numSamples) {
            samples[i] = Math.sin(2.0 * Math.PI * i / (sampleRate / frequency.toDouble()))
        }

        // המרה לפורמט שהרמקול מבין
        var idx = 0
        for (dVal in samples) {
            val valShort = (dVal * 32767).toInt()
            buffer[idx++] = (valShort and 0x00ff).toByte()
            buffer[idx++] = (valShort.toInt() shr 8 and 0x00ff).toByte()
        }

        val audioTrack = android.media.AudioTrack(
            android.media.AudioManager.STREAM_MUSIC,
            sampleRate,
            android.media.AudioFormat.CHANNEL_OUT_MONO,
            android.media.AudioFormat.ENCODING_PCM_16BIT,
            buffer.size,
            android.media.AudioTrack.MODE_STATIC
        )
        audioTrack.write(buffer, 0, buffer.size)
        audioTrack.play()

        // שחרור זיכרון אחרי ההשמעה
        audioTrack.notificationMarkerPosition = numSamples
        audioTrack.setPlaybackPositionUpdateListener(object : android.media.AudioTrack.OnPlaybackPositionUpdateListener {
            override fun onPeriodicNotification(track: android.media.AudioTrack) {}
            override fun onMarkerReached(track: android.media.AudioTrack) {
                track.release()
            }
        })
    }

    /**
     * [Function] startSimulation - Begins the "Simon Says" simulation sequence.
     * This function runs as a Coroutine, allowing for delays without freezing the app's UI.
     * It clears the previous sequence, generates a new one, and shows it to the user
     * by flashing the buttons.
     */
    fun startSimulation() {
        EditText.postDelayed({EditText.text = "My turn"},600) // Update the UI to show it's the computer's turn.
        // Disable the touch listeners on all buttons to prevent user input during the simulation.
        buttonDataList.forEach { it.button.setOnTouchListener(null) }

        // Launches an asynchronous task tied to the Activity's lifecycle.
        lifecycleScope.launch {
            sequenceToRemember.clear() // Clear the sequence from the previous round.
            delay(600)
            count = 0 // Reset the user's press counter for the new round.
            textCount.text = "$count" // Update the count display.

            // This loop runs 'number' times to generate and display the sequence.
            repeat(number) {
                delay(1500) // Pause for 1.5 seconds between each flash.
                val randomButtonData = buttonDataList.random() // Select a random button from the list.
                sequenceToRemember.add(randomButtonData.button) // Add the chosen button to the sequence to be remembered.
                // Call the function to simulate a click (change color and back) on the chosen button.
                simulateClick(randomButtonData.button, randomButtonData.pressedColor, randomButtonData.normalColor)
            }
            delay(1200) // A short pause after the entire sequence is shown.

            // After the simulation is complete, re-activate the touch listeners so the user can play.
            buttonDataList.forEach { data ->
                touchListener(data.button, data.normalColor, data.pressedColor)
            }
            number++ // Increment the sequence length for the next round (if the user succeeds).
        }
    }

    /**
     * [Function] touchListener - Sets up a listener for touch events on a specific button.
     * It defines what happens when the user presses down on the button (checks for correctness)
     * and when they release it.
     * @param button The button to listen to.
     * @param normalColor The button's default color.
     * @param pressedColor The color to display when the button is pressed.
     */
    @SuppressLint("ClickableViewAccessibility")
    fun touchListener(button: Button, normalColor: String, pressedColor: String) {
       EditText.postDelayed({EditText.text = "Your turn - repeat"},600)  // Update the UI to show it's the user's turn.
        // Defines the action in response to a touch event.
        button.setOnTouchListener { _, event ->
            when (event.action) {
                // Event: The user has placed their finger on the button.
                MotionEvent.ACTION_DOWN -> {
                    button.setBackgroundColor(Color.parseColor(pressedColor)) // Change the background to the "pressed" color.
                    val tone = buttonDataList.find { it.button == button }?.tone
                    tone?.let { playTone(it) }
                    // Check if the sequence is valid and the user is still within the sequence length.
                    if (sequenceToRemember.isNotEmpty() && count < sequenceToRemember.size) {
                        // Check if the pressed button is the correct one in the sequence.
                        if (button == sequenceToRemember[count]) {
                            count++ // Increment the correct press counter.
                            textCount.text = "$count" // Update the display.

                            // If this was the last correct press in the sequence, the user has won the round.
                            if (count == sequenceToRemember.size) {
                                bestScore = maxOf(bestScore, count) // Update best score if the current score is higher.
                                buttonDataList.forEach { it.button.setOnTouchListener(null) } // Disable buttons temporarily.
                                button.postDelayed({
                                    button.setBackgroundColor(Color.parseColor(normalColor)) // Change the background to the "pressed" color.
                                    startSimulation() // Start the next, longer round.
                                }, 100)
                            }
                        } else {
                            // Wrong button pressed — Game Over.
                            textCount.text = "Game Over"
                            //Toast.makeText(this, "Game Over", Toast.LENGTH_SHORT).show()
                            val resultIntent = Intent()
                            resultIntent.putExtra("bestScore", bestScore) // Prepare to send the best score back.
                            setResult(Activity.RESULT_OK, resultIntent) // Set the result to be returned to the previous activity.
                            textCount.postDelayed({
                                finish() // Close the activity after 5 seconds
                            }, 1000)
                        }
                    }
                }
                // Events: The user has lifted their finger, or the touch was cancelled.
                MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                    button.setBackgroundColor(Color.parseColor(normalColor)) // Revert the background to the normal color.
                }
            }
            // Return 'true' to indicate that the touch event has been handled here and should not be processed further.
            true
        }
    }

    /**
     * [Function] simulateClick - Simulates a button press by changing its color for a fixed duration.
     * This is used to show the user the sequence they need to remember.
     * @param button The button to be simulated.
     * @param pressedColor The color to show when the button is "pressed".
     * @param normalColor The default color the button will return to.
     */
    fun simulateClick(button: Button, pressedColor: String, normalColor: String) {
        // Immediately change the button's color to the "pressed" state.
        button.setBackgroundColor(Color.parseColor(pressedColor))
        val tone = buttonDataList.find { it.button == button }?.tone
        tone?.let { playTone(it) }
        // Use the postDelayed handler to run code after a delay without blocking the main UI thread.
        button.postDelayed({
            // Return the button to its normal color after a 1-second delay.
            button.setBackgroundColor(Color.parseColor(normalColor))
        }, 600) // 1000 milliseconds = 1 second.
    }
}
